typedef enum TOK {
  TOK_LCURLY,
  TOK_RCURLY,
  TOK_LPAREN,
  TOK_RPAREN,
  TOK_SEMICOL,
  TOK_COLON,
  TOK_QMARK,
  TOK_RETKEY,
  TOK_INTKEY,
  TOK_IFKEY,
  TOK_ELSEKEY,
  TOK_ID,
  TOK_INTLIT,
  TOK_BITCOMP,
  TOK_LOGNEG,
  __BIN_ARITH_START__,
  TOK_NEGATION,
  TOK_ADD,
  TOK_MULTIPLY,
  __BIN_ARITH_END__,
  __BIN_RELAT_START__,
  TOK_LOGEQ,
  TOK_LOGNEQ,
  TOK_LOGLE,
  TOK_LOGLEQ,
  TOK_LOGGE,
  TOK_LOGGEQ,
  __BIN_RELAT_END__,
  __BIN_JUNC_START__,
  TOK_LOGAND,
  TOK_LOGOR,
  __BIN_JUNC_END__,
  TOK_DIVIDE,
  TOK_UNK,
  TOK_ASSIGN
} TOK;

typedef struct Token {
  TOK kind;
  char *literal;
} Token;
